# Mapping hosts path with jeansdev.org sources into containers
# This is roughly equivalent to
# lxc config device add <CONTAINER-NAME> install disk path=/root/install source=~/homekube/src/installation/k8s/lxc/node
# lxc config device add <CONTAINER-NAME> homekube disk path=/root/homekube source=~/homekube/src/
config: {}
description: "LXD Profile for Mapping Homekube's folders into containers"
devices:
  install:
    path: /root/installation
    source: /home/ubuntu/homekube/src/installation/k8s/lxc/node
    type: disk
  homekube:
    path: /root/homekube
    source: /home/ubuntu/homekube/src
    type: disk
name: homekube
used_by: []
